### ISSUE TITLE
ds2(s) AI scripts

### ISSUE THREAD

**Issue by r3sus** [thefifthmatt/ESDLang#2]
Hello and thanks for the project!
I'd like to propose to add the ds2(s) AI scripts, even tho they're complicated. Personally, I had issue figuring which AI script to which character corresponds. So it would be good to make some kind of AI-char reference or the guidance on figuring that. 
The 2nd idea is to add ds2 (vanilla) scripts for comparison with ds2s (both AI and event).
Please, have a look.
Thanks.

**Comment by gracenotes** [comment]
I have ended up moving away from MSB-based metadata because it is fairly fragile and overkill for most use cases. I don't have a dump of names for DS2 so this might be something a DS2 modder might have to do, similar to https://soulsmods.github.io/data/er/entities.html for Elden Ring which includes the enemy think id for AI script lookup.

Also I removed the `examples` directory, because including all games would take up 160MB, but I am adding a dump of all esd files (including AI files, for both DS2 and DS2S) to all new releases.
